name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout your code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    # 3. Terraform Init
    - name: Terraform Init
      run: terraform -chdir=Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # 4. Run tfsec for Terraform security
    - name: Run tfsec (Terraform Security Scan)
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        working_directory: ./Terraform

    # 5. Run Trivy on Dockerfile
    - name: Run Trivy scan on filesystem
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'


    # 6. Apply Sealed Secret to cluster
    - name: Apply Sealed Secret
      run: kubectl apply -f Terraform/sealed-secret.yaml

    # 7. Terraform Plan
    - name: Terraform Plan
      run: terraform -chdir=Terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # 8. Terraform Apply
    - name: Terraform Apply (optional)
      if: github.ref == 'refs/heads/main'
      run: terraform -chdir=Terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
