name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout your code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # 3. Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    # 4. Terraform Init
    - name: Terraform Init
      run: terraform -chdir=Terraform init

    # 5. Run tfsec for Terraform security
    - name: Run tfsec (Terraform Security Scan)
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        working_directory: ./Terraform

    # 6. Run Trivy on the codebase
    - name: Run Trivy scan on filesystem
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'

    # 7. Set up kubectl with base64 kubeconfig
    - name: Set up kubectl with KUBECONFIG
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

    # 8. Apply Sealed Secret to Kubernetes
    - name: Apply Sealed Secret
      run: kubectl apply -f Terraform/sealed-secret.yaml

    # 9. Terraform Plan
    - name: Terraform Plan
      run: terraform -chdir=Terraform plan

    # 10. Terraform Apply (optional)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform -chdir=Terraform apply -auto-approve
